.TH "LodePNG User Manual" 1 "04 Nov 2016" "LodePNG documentation"

.SH NAME
pnglossy

.SH DESCRIPTION
Lossy reencode a PNG image.
 Based of LodePNG library.

.SH SYNOPSIS
pnglossy [filename.png] [output.png] [quant={1-256}]

.SH EXAMPLE
pnglossy sample.png lossy.png 32

.SH COPYRIGHT
Copyright 2005-2013 Lode Vandevenne.
 All rights reserved.

.SH SEE ALSO
 pngdetail(1), pngreencode(1), pnginfo(1), pngcheck(1).

.SH CONTACTS
 Website: http://lodev.org/lodepng/
 Autors: Lode Vandevenne <lode.vandevenne@gmail.com>
