.TH LodePNG 1 "05 Aug 2019" "0.20190805" "User Manual"

.SH NAME
pnglossy

.SH DESCRIPTION
Lossy reencode a PNG image.
 Based of LodePNG library.

.SH SYNOPSIS
pnglossy [filename.png] [output.png] [quant={1-8}]

.SH EXAMPLE
pnglossy sample.png lossy.png 4

.SH COPYRIGHT
Copyright 2005-2013 Lode Vandevenne.
 All rights reserved.

.SH SEE ALSO
 pngdetail(1), pngreencode(1), pnginfo(1), pngcheck(1).

.SH CONTACTS
 Website: http://lodev.org/lodepng/
 Autors: Lode Vandevenne <lode.vandevenne@gmail.com>
