.TH LodePNG 1 "05 Aug 2019" "0.20190805" "User Manual"

.SH NAME
pngreencode

.SH DESCRIPTION
Reencode a PNG image.
 Based of LodePNG library.

.SH SYNOPSIS
pngreencode [filename.png] [output.png]

.SH EXAMPLE
pngreencode sample.png reencode.png

.SH COPYRIGHT
Copyright 2005-2013 Lode Vandevenne.
 All rights reserved.

.SH SEE ALSO
 pngdetail(1), pnglossy(1), pnginfo(1), pngcheck(1).

.SH CONTACTS
 Website: http://lodev.org/lodepng/
 Autors: Lode Vandevenne <lode.vandevenne@gmail.com>
